config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "main#index"

  resource :registration, only: [ :new, :create ]
  resource :session, only: [ :new, :create, :destroy ]
  resource :password_reset, only: [ :new, :create, :edit, :update ]
  resource :password, only: [ :edit, :update ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
   attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  normalizes :email, with: ->(email) { email.strip.downcase }

  generates_token_for :password_reset, expires_in: 15.minutes do
      password_salt&.last(10)
  end

  generates_token_for :email_confirmation, expires_in: 24.hours do
      email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to do that :/" unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end

  helper_method :current_user # This makes the method available in views

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
    # !! current_user # This is a double negation that converts the object to a boolean
  end
  helper_method :user_signed_in? # This makes the method available in views
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :set_user_by_token, only: [ :edit, :update ]

  def new
    # Render the password reset form
  end

  def create
    if (user = User.find_by(email: params[:email]))
        PasswordMailer.with(
            user: user,
            token: user.generate_token_for(:password_reset)
        ).password_reset.deliver_later
    end

    redirect_to root_path, notice: "If your email is in our system, you will receive a password reset link shortly."
  end

  def edit
    # Render the edit password form
  end

  def update
    if @user.update(password_params)
        redirect_to new_session_path, notice: "Password updated successfully. Please log in."
    else
        # We don't need flash messages here because the form already displays the error messages directly
        render :edit, status: :unprocessable_entity
    end
  end

  private


    def password_params
      params.expect(user: [ :password, :password_confirmation ])
      # params.require(:user).permit(:password, :password_confirmation)
    end

    def set_user_by_token
      @user = User.find_by_token_for(:password_reset, params[:token])
      redirect_to new_password_reset_path, alert: "Invalid or expired token. Please try again!" unless @user.present?
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!

  def edit
    # Render the password form
  end

  def update
    if current_user.update(password_params)
      redirect_to edit_password_path, notice: "Password was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.expect(user: [ :password, :password_confirmation, :password_challenge ]).with_defaults(password_challenge: "")
    # params.require(:user).permit(:password, :password_confirmation, :password_challenge).with_defaults(password_challenge: "")
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end


    def new
        @user = User.new
    end

    def create
        @user = User.new(registration_params)
        if @user.save
            login @user
            redirect_to root_path, notice: "Account created successfully."
        else
            render :new, status: :unprocessable_entity
        end
    end

    private


    def registration_params
        params.expect(user: [ :email, :password, :password_confirmation ])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      login user
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "Logged out successfully"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Auth App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <div> <%= notice%> </div>
    <div> <%= alert%> </div>

    <% if user_signed_in? %>
    <%=link_to "Edit Password", edit_password_path %>
    <%= button_to "Log Out", session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign Up", new_registration_path %>
    <%= link_to "Log In", new_session_path %>
    <% end %>
    <%= yield %>
</body>

</html>

app/views/main/index.html.erb
<h1> Homepage </h1>

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>

<%=form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
<% if form.object.errors.any? %>
<% form.object.errors.full_messages.each do |message|%>
<div> <%= message %> </div>
<% end %>
<% end %>

<div>
    <%= form.label :password, "New Password" %>
    <%= form.password_field :password, autocomplete: "new-password" %>
</div>

<div>
    <%= form.label :password_confirmation, "Password Confirmation" %>
    <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
</div>

<div>
    <%= form.submit "Reset Your Password" %>
</div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset You Password</h1>

<%= form_with url: password_reset_path do |form| %>
<div>
    <%= form.label :email %>
    <%= form.email_field :email, autofocus: true, autocomplete: "email" %>
</div>

<div>
    <%= form.submit "Reset Password" %>
</div>
<% end %>